FROM oci.klar.sh/bow-base:latest

COPY packages.zoom.list /etc/distroboxen.packages.zoom.list

# Filter out comments and empty lines from package list and install
RUN pacman --noconfirm -Syyuu --needed \
		$(grep -vE '(^#|^\s*$)' /etc/distroboxen.packages.zoom.list) && \
	yes | LC_ALL=en_US.UTF-8 pacman -Scc
